name: build-project
on: [push]
jobs:
  build-on-windows:
    runs-on: windows-2019
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build --config Debug
  build-on-osx:
    runs-on: macos-11
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build -j$(sysctl -n hw.logicalcpu)
